version: 1
formatters:
  custom_logging01:
    format: '%(asctime)s - %(levelname)8s - : [%(file_name)s#%(func_name)s:%(line_no)d] %(message)s'
loggers:
  custom_logging01:
    handlers: [console]
    level: DEBUG
    qualname: custom_logging01
    propagate: no
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: custom_logging01
    stream: ext://sys.stdout
root:
  level: ERROR
  handlers:
